msoos/cryptominisat

cryptominisat4/bva.cpp

Removes the following errors when compiling on OS X:
/Users/rion/cryptominisat/cryptominisat4/bva.cpp:182:66: error: no member named
'sqrt' in namespace 'std'; did you mean simply 'sqrt'?
*simplifier->limit_to_decrease -= 2*(long)m_cls.size()*(long)std::sqrt(m...
^~~~~~~~~
sqrt
/Users/rion/cryptominisat/cryptominisat4/bva.cpp:670:76: error: no member named
'log' in namespace 'std'; did you mean simply 'log'?
...-= (double)potential.size()*(double)std::log(potential.size())*0.2;
^~~~~~~~
log

Fix compilation on OS X

---

cryptominisat4/CMakeLists.txt

This way other CMake projects can pick up M4RI, even when it is installed locally.
Currently the imported target `m4ri` is exported, which will resolve to a locally installed m4ri library in `/usr/lib`, but will not work when m4ri is installed locally.
With this patch the full path to the library is exported.
This works, when m4ri, cryptominisat and the client using it (e.g. STP) are build on the same system but will fail when cryptominisat is packaged and used on a system with a different location. However currently this also only works when m4ri is installed system-wide on the new system.

link public against M4RI_LIBRARIES

---

src/watched.h

- used static_cast<> instead of chain of if/else's.
- initialized type member explicitly in default constructor.

watched: streamlined getType() method.

---

CMakeLists.txt

I had trouble compiling the Python interface in my setup (it seemed to pick up a compile flag from the system Python that the clang I was using did not support). Since I'm not using Python, I ended up adding an option to the CMake build to disable it, which might be useful to other people as well.

Add option to disable Python in CMake build

---

src/subsumestrengthen.cpp

Fix the issue reported by Clang:
```
warning: & has lower precedence than ==; == will be evaluated first
[-Wparentheses]
```

Fix interruption condition in handle_sub_str_with

---

src/searcher.cpp

Looks like commit 5a40d1b9c3053c14e1f4bfd6b92326b415ebdfec broke the
build on clang by indirectly removing math.h from the included header files.

Add missing include

---

src/cnf.cpp
src/searcher.cpp

When not using flags like DEBUG_RESOLV, some functions do nothing. This
was achieved by having an unconditional return in an `#ifndef`
statement. The return statement, however, makes the rest of the function
(intentionally) unreachable and triggers a warning when compiling with
clang. The solution is to restructure the affected functions slightly to
avoid these warnings.

Fix unreachable code warnings

---

python/CMakeLists.txt
python/setup.py.in

Use python-config to get the correct parameters for building/linking.
Limitation: flags returned by python-config cannot contain spaces
because spaces are used to split the flags.

Fix python build on OSX

---

scripts/travis-cmake.sh

Travis fails for pull requests because CMS_CONFIG=COVERAGE uses
$COVERTOKEN when uploading results to coveralls and $COVERTOKEN is not set.
Check if $COVERTOKEN is set and skip the result upload if it is not.

Only attempt coveralls upload if $COVERTOKEN set

---

src/streambuffer.h

Commit f10db78e23dd180abcab74f4e7d1beef99035e89 changed the while loop
condition slightly (accepting '\n' instead of '\t'), leading to failing
tests.

Fix while loop condition in skipWhitespace()

---

src/CMakeLists.txt

Otherwise, compiler may pick headers from installed cmsat.

Put -I flag for generated headers earlier in the command line.

---

CMakeLists.txt
scripts/xxd-alike.py
src/CMakeLists.txt

Python runtime is more common on Windows than Vim (on Linux its a wash), so I suggest trading dependency on vim for dependency on Python runtime. This PR implements required part of xxd in Python and is Python 2 and Python 3 compatible.
This could also likely be implemented in CMake, but not by me.
Related to #406

Replace dependency on XXD with simple Python script

---

src/cryptominisat.cpp

This moves potential errors from runtime to compile time, and also
catches copy assignment errors.

Properly delete CMSatPrivateData copy constructor (and assignment!)

---

src/reducedb.h

`const double` as a return type makes no sense and the method is const, so I moved it around to silence a warning from gcc.

Fix const placement in ReduceDB::get_total_time()

---

CMakeLists.txt
src/bva.cpp
src/constants.h
src/features_to_reconf.cpp
src/ipasir.cpp
src/main_simple.cpp
src/occsimplifier.cpp
src/searcher.cpp
src/searcher.h
src/simplefile.h

Also fixes most of the resulting warnings. There are some 30 warnings
left, but they should be easy to fix with some mechanical work.

Enable W4 when compiling with MSVC

---

src/searcher.cpp

There was a typo in a loop iterator name which was introduced recently. (#411)

Correct loop iterator name

---

CMakeLists.txt

The statement "leads to faster system" is a bit confusing. One immediately understands this as "no statistics ⇒ faster system" but it could also mean "no statistics. Too bad, they would lead to a faster system." I slightly stumbled upon this here https://github.com/conda-forge/staged-recipes/pull/5185.

Clarify performance impact of detailed statistics

---

python/src/pycryptosat.cpp
src/occsimplifier.h

- In the earlier pull request #478, the `time_limit` was updated from long->double in nearly ever case except [one](https://github.com/msoos/cryptominisat/pull/478/files#diff-437bd5e874df2ba9f9ced39b13eee9abR101). This also fixes the inconsistent use of `time_limit` versus `timelimit` in the [error string](https://github.com/msoos/cryptominisat/pull/478/files#diff-437bd5e874df2ba9f9ced39b13eee9abR111).
- Fixes a new [GCC](https://gcc.gnu.org/ml/gcc-patches/2017-04/msg00469.html)/Clang warning about `-Wextra-semi` in the occ simplifier code. 
Ran the test cases locally and it builds and passes, but not sure if Python gets tested. :)

Fix warnings: long vs. double, extra semicolon in class definition.

---

python/CMakeLists.txt

CMake normally supports `DESTDIR` installation of files--this is used (typically by running something like `make install DESTDIR=some/tmp/dir`) to install packages into an alternate root, usually for packaging purposes.
However, when packaging cryptominisat the Python module is not installed into a supplied `DESTDIR`.  This could be worked around in principle by disabling CMake from installing the Python module, and supplying the necessary commands manually.  But better to just fix this directly.  This solution worked for me.

Fix DESTDIR support for installing the Python module

---

CMakeLists.txt

Under 5.6.0, cmake configures the destination for the man pages to be `$PREFIX/man/`; however, man pages usually reside in `$PREFIX/share/man`. See FILES in `man man` ([here](http://man.he.net/?topic=man&section=all)).

Fix man page install location

---

python/CMakeLists.txt

Fixes regression against #490 introduced by 63a629f5e363a467abff1fa29becf42fe55b79f9 and b3cd73f369d4ea14f12824f0f3c4a06a9aa0e1b1 `CMAKE_INSTALL_PREFIX` is *not* the same thing as `DESTDIR`, and `--prefix` is not the same thing as `--root` (though both can coexist).
The installation path ends up being `<root><prefix>/<libdir>/<pythonX.Y>/site-packages/`.  By default root is normally `/` but the point of `DESTDIR` is to change that to an alternate path (e.g. for packaging).

Fix DESTDIR support for the Python package again

---

README.markdown

Dropped when #493 was closed were changes to the README for Ubuntu. Your (admittedly old) Debian [control](https://github.com/msoos/cryptominisat/blob/bf3ec2968e488e5d4c31da08d27e5e2dda4c3d1d/debian/control#L5) listed zlib as a dependency as does the Fedora [spec](https://src.fedoraproject.org/rpms/cryptominisat/blob/master/f/cryptominisat.spec#_21). 
(Other than that, I'm fine with dropping the Fedora-specific changes to the README).
Thanks!

Update README to reflect zlib dependency

---

python/src/pycryptosat.cpp
scripts/performance/addclause.py

Adds `max_var=0` keyword argument to `add_clauses` in the Python interface.
This lets one specify the maximum variable number that is used in the given clauses and in turn enables speedups in case a high number of new variables is added.
xrefs: https://github.com/msoos/cryptominisat/pull/515#issuecomment-415856002, https://github.com/msoos/cryptominisat/pull/515#issuecomment-415901769

python: add_clauses: add max_var=0 kwarg

---

src/solver.cpp
src/solver.h

This is a follow-up to https://github.com/msoos/cryptominisat/pull/515#issuecomment-415870385 ff. and https://github.com/msoos/cryptominisat/commit/3baaafe678057a043f93569505da72071ea79a52.
We can avoid copying the input clause not only in `add_clause_int` but also in `addClause`, which gives another speed up.

Solver::addClause: use add_clause_int_tmp_cl

---

python/src/pycryptosat.cpp
scripts/performance/addclause.py

Adds support to the `add_clauses` method of the Python interface for passing over clauses as a flat `array.array` of integers. Each clause has to be terminated by a zero, such that the integer array represents a stream of zero separated clauses.
In a subsequent step, this could be improved upon to support not only `array.array` instances but additionally support the [Python C-API buffer protocol](https://docs.python.org/3/c-api/buffer.html). If anyone with more experience around the Python C-API wants to volunteer for it, this would be highly appreciated!

python: add_clauses: support array.array as input

---

python/src/pycryptosat.cpp

I was thinking it could make sense to use `array.itemsize` instead of `array.typecode` to decide which type the array is, in case different compilers (with `LP64` vs `LLP64`) were used to compile the interpreter and the extension. (The `typecode` is still checked to make sure we get an array of signed integers.)
It could very well be that this is not important. But it also doesn't hurt to do this :).

python: add_clauses_array: check itemsize

---

python/tests/test_pycryptosat.py

Fixes https://github.com/msoos/cryptominisat/pull/520#issuecomment-416742392.
Explanation: `from __future__ import unicode_literals` is used for forward compatibility to Python 3 (which is a good thing :+1:) and causes all string literals in the module to be of type `unicode` instead of `str`. For Python 3 `str` is equal to `unicode`. For Python 2 `str` is `bytes`, though, and `array.array` expects the first argument to be of type `str`, i.e., `bytes` for PY2.
Through a simple wrapper with `str(typecode)`, we can ensure that the argument becomes of type `bytes`.

python: tests: ensure str typecode for PY2

---

src/solver.cpp
src/solver.h

I've just been too curious whether a profiler would show some more obvious places where performance tweaks can be applied ^^.
Here are two additional small uncontroversial improvements for `add_clauses` and probably the last contributions from my side in regards to speeding that up. With that we have:
`master` at https://github.com/msoos/cryptominisat/commit/e4803df9d14ea74c820a91b988b4d1dac0ad9dd1
```
$ ./scripts/performance/addclause.py
setup CMS     array 0.248 0.249 0.249 0.250 0.257
setup CMS     list  0.419 0.425 0.433 0.441 0.444
setup Pycosat array 0.182 0.183 0.185 0.187 0.187
setup Pycosat list  0.250 0.252 0.252 0.257 0.261
solve CMS     array 0.097 0.097 0.097 0.097 0.098
solve CMS     list  0.098 0.106 0.108 0.108 0.110
solve Pycosat array 1.597 1.604 1.606 1.608 1.613
solve …
```

Add clauses speedups

---

python/src/pycryptosat.cpp.in

Not sure if you're interested in this. 
I'd like a way to set timeouts for individual solves (versus all solves) -- the first solve takes the most time, and subsequent solves take less. (I'm also not particularly interested in finding *everything* as that's too big of a space. Just until it starts taking too long for some arbitrary metric...)
I figured I'd copy the semantics of the `Solver(...)` constructor and apply it to `Solver.solve(...)` in case others wish to add per-solve conflict limits, verbosity, or ~change the number of threads.~ **edit:** it appears that changing the number of threads can't be done after adding clauses.
After each solve, the `Solver`-level defaults are restored.
Since these are keyword arguments, these shouldn't break any existing program. 
(WIP since I'd like …

[WIP] Per-solve timeouts in the Python API

---

python/src/pycryptosat.cpp.in

This changes all references to `arg[n]` to the specified `kwarg` name, moves
types to be with their parameter descriptions, and adds a missing
`max_vars` parameter to `add_clauses(...)`.
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`

Fix arguments in Python docstrings

---

python/CMakeLists.txt

When the user builds CryptoMiniSat inside a virtualenv and runs
`make install`, they reasonably expect pycryptosat to be installed inside
the virtualenv. However, it actually is installed to the system prefix
(`/usr/local`), which the virtualenv blocks.
Fix this behavior, but retain `CMAKE_INSTALL_PREFIX` if not building
inside a virtualenv. However, `PYCRYPTOSAT_INSTALL_PATH` can be used to
provide a definitive override.
Resolves: #550
Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>

[pycryptosat] Support virtualenv installation

---

python/src/pycryptosat.cpp.in
python/tests/test_pycryptosat.py

This lets the user query SATSolver::get_conflict() from pycryptosat,
exposing the result as a dict of bools, representing the variable and
the incorrect value.
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`

Expose get_conflict in pycryptosat

---

src/cryptominisat.cpp

In the core of CMS (e.g., `Solver::iterate_until_solved`), the value `conf.maxTime` is checked against `cpuTime`, rather than `s.get_stats().cpu_time`.
This PR modifies the setting of `conf.maxTime` to calculate an offset from `cpuTime` to correctly match its later uses.

Modify the maxTime value to be based off cpuTime (process time) rather than 'solver time', to correctly match the subsequent uses later on

---

.gitignore
cmsat_tablestructure.sql
src/prober.cpp
src/searcher.cpp
src/searcher.h
src/sqlitestats.cpp
src/sqlitestats.h
src/sqlstats.h

Created a variable old_glue in handle_conflict. It passes through function calls and reaches dump_clause_stats to get stored in clauseStats table in the database.

Saving glue of unminimised clause in SQL

---

python/src/pycryptosat.cpp.in

`pycryptosat` has no module members currently, but still defines an empty
`module_methods` struct. Remove it.
`Py_InitModule3` has supported a `NULL` second parameter since Python 2.3:
https://docs.python.org/2/c-api/allocation.html#c.Py_InitModule3
`PyModuleDef` also supports a `NULL` `m_methods` parameter:
https://docs.python.org/3/c-api/module.html#c.PyModuleDef.m_methods
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`

Remove module members definition

---

python/src/pycryptosat.cpp.in

These changes help to make `pycryptosat` conform to common practices in
other Python/C API modules, such as those in `cpython`. There are three changes in this commit. 
1. Use `PyModule_AddStringConstant` to add `__version__` to the module.
2. Rewrite error checking to occur on the call and not at the end, allowing us to do (3).
3. Remove error mangling if an error occurred "somewhere".
I'm not sure why the diff looks like how it does, but that's fine.
Python since at least 2.5 has supported the `PyModule_AddStringConstant`
helper. Various modules in `cpython` use it (such as [`_csv`](https://github.com/python/cpython/blob/master/Modules/_csv.c#L1641-L1644), [`zlib`](https://github.com/python/cpython/blob/master/Modules/zlibmodule.c#L1458), …

Cleanup pycryptosat initialization

---

python/src/pycryptosat.cpp.in

The contents of `Solver_members` seem to be left over from a different
time and seem unrelated to CryptoMiniSat. Remove them. In the
`pycryptosat_SolverType` struct, set the `tp_members` pointer to `NULL`.
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`

Remove Solver_members definition

---

python/src/pycryptosat.cpp.in

(I made it four; this was the remaining change from #564 not covered by the other three PRs I opened this morning). 
`Solver_new` is unused due to its replacement with [`PyType_GenericNew`](https://github.com/msoos/cryptominisat/commit/9a04102ea72b6b9c0d82c7981dc5928af375a5c8#diff-f302d59ffbb0986caa6e74370a6de11fR320). This
means that `Solver_new` is dead code. According to the Python
[documentation](https://docs.python.org/3/reference/datamodel.html#object.__new__), `__new__` should initialize a new instance of a type,
similar to the following C code:
```c
my_ptr = calloc(...);
MyType_init(my_ptr, ...);
return my_ptr
```
However, `PyType_GenericNew` doesn't call our `tp_init` on the newly
created object. This means the resulting instance isn't initialized,
forcing us to initialize it …

Remove unused Solver_new implementation

---

CMakeLists.txt
src/cryptominisat.cpp
src/distillerlong.cpp
src/main.cpp
src/main_exe.cpp
src/occsimplifier.cpp
src/searcher.cpp
src/sls.cpp
src/solverconf.h
src/varupdatehelper.h
src/xorfinder.cpp

As part of some different work, I played with warnings that are currently not in use by CMSat and noticed that `-Wextra-semi-stmt` leads to 131 extra warnings, most of which were caused by 3 instances in header files that are then included by many different TUs.

Fix extra semicolons in various places and enable the corresponding warning

---

src/cryptominisat.cpp
src/cryptominisat.h.in

As per #581, this provides const overloads for the existing functions. If there is no fear of breaking external dependencies, the non-const overloads can be removed, otherwise they can be marked as deprecated and removed in the next major release.
Closes #581

Provide const overloads for get_sum_{conflicts,decisions,propagations}

---

src/MersenneTwister.h

The `register` keyword as a storage specifier keyword has been
deprecated in C++11 and C++17 actually removes it from the language
completely, pending future reuse.
The rationale is that it is a weak hint that is pretty much ignored
by all major modern compilers, and the effect of the specifier is
implicit in C++ anyway.
This also fixes all of the `-Wdeprecated-register` instances in CMSat.

Remove 'register' storage specifier from variable declarations in MT

---

src/walksat.cpp
src/walksat.h

As it turns out, there were significant changes to `walksat.cpp` between the version we use (latest releaes), and current master. However, some places still used `found_solution` as a number, rather than as a boolean variable, so this fixes (most) of them.
Also removed a variable that was written to, but never read.
Fixes #589

Don't use bool as a number

---

src/shareddata.h

This forbids the undesirable construct during compilation, instead of waiting to cause failure at runtime.
There are certain obscure cases where the old construct is the right choice involving `std::function` and other guaranteed-copyable wrappers, but since the code still compiles, it obviously is not the case here.

Properly forbid copies of SharedData::Spec

---

src/varreplacer.cpp

The problem is that the entry type of a `std::map<K, V>` is
`pair<const K, V>`, rather than `pair<K, V>`. Because the latter
is constructible from the former via a copy constructor, the old
code compiled, but made an extra copy during iteration.

Prevent an extra copy when iterating through map

---

CMakeLists.txt
src/CMakeLists.txt
src/drat.cpp
src/drat.h
src/hyperengine.cpp
src/hyperengine.h
src/sqlstats.cpp
src/sqlstats.h

This PR sweets out most instances of weak vtables.
A class has weak vtable when it has no out-of-line definitions of virtual functions. This means that the compiler cannot pick an authoritative TU to contain the class's vtable and RTTI structures. Because of this, the compiler has to emit all of this in every TU that touch the header, bloating the size of object files and increasing compilation times, and link times (because the linker has to deduplicate the vtables and RTTI structures).

Reduce weak vtables

---

.gitignore
src/cryptominisat_c.cpp
src/cryptominisat_c.h.in

Does what the title says. cmsat_set_verbosity is included in the C API.

Extend C API with set_verbosity and print_stats

---

README.markdown
src/main.cpp
src/solver.cpp

In the current release, the documentation of the `reconf` parameter in the readme.md and command line help state that `reconf` can be set to 0..15. In fact, only the values 3,4,6,7,12,13,14,15,16 are supported.
This patch updates the documentation to tell users that values 3,4,6,7,12,13,14,15,16 are supported.
(Note 1: I didn't update the autotune-related python scripts to work with the new reconf values.)
(Note 2: Happy holidays!)

Update documentation of the reconf parameter

---

.travis.yml

relates to https://github.com/msoos/cryptominisat/issues/617
Adding osx 10.13 into build matrix.

build: add osx 10.13 for cross compilation

---

python/CMakeLists.txt

in the nix build environment we don't need to explicitly pass
the osx sdk path. In fact it actually breaks the build.

fix build on nix-darwin

---

.travis.yml
scripts/travis-cmake.sh
src/packedmatrix.h

I have also added a travis option to test a build using a mingw32 cross-compiler on linux, but the travis script also builds other things like drat-trim, and I don't know how to prevent this. The tests are also disabled since it is not possible to run the produced exe file on linux. Ideally, a mingw32 build should run on windows, but I do not have a windows machine to test the setup.

A patch to address #625

---

src/ipasir.cpp
tests/ipasir_test.cpp

This PR fixes two issues with the IPASIR implementation:
* **`ipasir_val` for negative literals:** Currently, `ipasir_val(s, lit)` returns `-lit` if the variable `v` of `lit` is assigned `false`, `lit` if `v` is assigned `true` and 0 otherwise. However, the IPASIR spec requires checking the assignment of the literal, not that of the variable. The current implementation works fine for positive literals, but returns invalid values for negative ones (flipping `lit` when the variable of `lit` is assigned `false` even when `lit` < 0).
**New behavior:** `ipasir_val(s, lit)` returns `-lit` if `lit` is assigned `false`; `lit` if `lit` is assigned `true` and 0 otherwise. 
* **`ipasir_assume` for literals not occurring in any clause:** Cryptominisat refuses assumptions not occurring in any clause …

Bugfixes for ipasir_val() and ipasir_assume()

---

README.markdown

`(description)[URL]` should be `[description](URL)`.

README: fix markdown link syntax in Rust section

---

python/CMakeLists.txt

CMake complained about COMPARE needing 4 arguments when I tried to generate using MSYS; looks like the problem is that one of the Python flags is an empty string and CMake thinks the argument is missing. Quoting the flags fixes it.

Quote some flags in python/CMakeLists.txt

---

src/CMakeLists.txt

This PR addresses an issue that arises if one installs `cryptominisat5` to a custom location outside of the standard search paths (e.g. when building as a dependency of another projection within an cmake `ExternalProject`).
What I would like to do is use libcryptominisat5 via `find_package(cryptominisat5)` and `target_link_libraries(MyTarget cryptominisat5)`. This fails right now, because the `cryptominisat5` target does not define its include directories, thus one needs to add the include directory manually (either to `MyTarget` or `cryptominisat5`.
This PR fixes this issue by setting the public include directory for the `cryptominisat5` target.

Make exported target have an include dir

---

src/main_exe.cpp

Resolves second issue discussed in #650 where musl wouldn't compile since `feenableexcept` isn't available there. Attempted to use _GNU_SOURCE as mentioned by @andrewvaughanj but was not successful. 
Used this method to fix in downstream here: https://github.com/JuliaPackaging/Yggdrasil/pull/2911 where I'm packaging CMS using https://binarybuilder.org/ for Julia!

Switch __GNUC__ to __GLIBC__ to support musl

---

CMakeLists.txt

Attempt to fix the same issue as in https://github.com/stp/stp/pull/413

MSVC: Fix overriding '/MTd' with '/MT'

---

CMakeLists.txt
src/CMakeLists.txt

In this PR I modernized Boost usage by using [imported targets](https://cmake.org/cmake/help/latest/module/FindBoost.html#imported-targets). But the feature was introduced in CMake 3.5, so I bumped the version. But KLEE uses [the same version](https://github.com/klee/klee/blob/0ba95edbad26fe70c8132f0731778d94f9609874/CMakeLists.txt#L13), so I hope it's okay :)
Made the same PR for [stp](https://github.com/stp/stp/pull/418).

Modernize Boost usage

---

src/main.cpp

Fixes #665
Print a solution count for the last solution.
For example
>c Number of solutions found until now:      2
>c maxsol reached
The message need to printed outside of multi_solutions() as multi_solutions returns with the last solution still to be printed,
and the message should be printed after the soliution, like for the other messages.
Also the new message is only printed when more than one solution is requested, to avoid clutter.

Issue #665 solution count print

---

CMakeLists.txt

Add a CMake version file to the default cmake configuration, which enables other cmake packages to use this package when there are version constraints.

Add CMake version file

---

tests/assump_test.cpp

Without this header, std::sort is not included directly in this header file, but transitively over the stp/googletest distribution, in the `include/gtest/internal/gtest-port.h` file, included by `include/gtest/internal/gtest-string.h`, included by `include/gtest/gtest.h`.
This change makes it easier to use a different GTest implementation, which is easier for some package management mechanisms.

Add <algorithm> header to assump_test.cpp

---

src/main_exe.cpp

Catch boost errors to avoid core dump in case of wrong command line parameters

Catch boost errors to avoid core dump in case of wrong command line parameters

---

src/alg.h
src/boundedqueue.h
src/bva.h
src/cardfinder.h
src/ccnr.h
src/cl_predictors_abs.h
src/clabstraction.h
src/clause.h
src/vmtf.h
src/watcharray.h
src/watcharray_handrolled.h
src/watched.h
src/xor.h
src/xorfinder.h

These files all assume the definition of types from <cstdint> but were getting those definitions transitively. GCC trunk (GCC13) no longer provides <cstdint> definitions transitively.

Include <cstdint> explicitly where required

---

python/src/pycryptosat.cpp

This pull request allows Solver.add_clauses to accept any contiguous buffer according to the [Python buffer protocol](https://docs.python.org/3/c-api/buffer.html) instead of just `array.array`. This possibility was already mentioned in #519.
The main advantage of the buffer protocol is that it can be implemented by third party modules as well. Thus, `add_clauses` will also work with numpy arrays for example. Another advantage is that the C side of the API is much simpler, and thus I was able to remove a bunch of code.
One limitation that remains in the current state of this pull request is that only contiguous buffers, i.e., buffers where the element are contiguous in memory, are supported. Non-contiguous buffers can be created in numpy, for example, if someone indexes only a column of a …

support buffer protocol in Solver.add_clauses

---

python/tests/test_pycryptosat.py

The `AssertNotEquals` alias has been removed

Fix tests with Python 3.12

---

src/mpicosat/mpicosat.c

A build failure with musl libc was reported on the Gentoo bug tracker:
https://bugs.gentoo.org/895118
The root cause is that the file sys/unistd.h is not included with musl. The POSIX standard include for unistd.h is simply <unistd.h>:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/unistd.h.html
and musl does provide that. Even in glibc, the sys-prefixed path is simply a wrapper:
```
$ cat /usr/include/sys/unistd.h
#include <unistd.h>
```
This commit changes the line,
```c
#include <sys/unistd.h>
```
to
```c
#include <unistd.h>
```
which should be more portable. In particular, it works with musl.

src/mpicosat/mpicosat.c: fix path to unistd.h

---

src/time_mem.h

std::bind1st is removed in C++17

Get rid of std::bind1st

---

setup.py
src/cnf.cpp
src/cnf.h
src/cryptominisat.cpp
src/cryptominisat.h
src/frat.h
src/idrup.cc
src/idrup.h
src/ipasir.cpp
src/ipasir.h
src/main.cpp
src/main_common.cpp
src/occsimplifier.cpp
src/propengine.h
src/searcher.cpp
src/solver.cpp
src/solver.h
src/solverconf.h
src/varreplacer.cpp

Sorry that it took me way too long to find the time to work on that…
Anyway, this is the rebased and squashed version of https://github.com/msoos/cryptominisat/pull/744

 IDRUP Support 

---

src/solvertypesmini.h

Should be faster and also semantically more sane. We never override this further.

 Use final, idea by @clonker
